baseurl      = "https://rb-x.github.io/"
title        = "rb-0x"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "in this blog you will find my CTF  writeups and some guided Tutorial "

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Welcome to my Cybersecurity Blog"
    subtitle = "Welcome to my Cybersecurity Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Riadh Bouchahoua - CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    
    

    [languages.en.params.logo]
      logoText = "./Riadh.sh"
      logoHomeLink = "/blog"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu


  [menu]



    [[menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/blog"
      weight = -100
      


    [[menu.main]]
      name = "Tutorial"
      post = "<span class='alert'>New!</span>"
      url = "/tutorial/"
      weight = -99


    [[menu.main]]
      identifier = "About me"
      name = "About me"
      url = "/"
      weight = -98
  
  
 